### Index
GET {{baseUri}}/categories HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

### Store
POST {{baseUri}}/categories HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "customer_id": 1,
    "description": "Categoria Criada via API/REST"
}

###Show
GET {{baseUri}}/categories/1 HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

###Update
PUT {{baseUri}}/categories/1 HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "description": "Categoria Atualizada via API/REST"
}

###Delete
DELETE {{baseUri}}/categories/1 HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}